version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  # from https://github.com/readthedocs/test-builds/blob/mdbook/.readthedocs.yaml
  commands:
    - cargo install mdbook
    - mdbook build --dest-dir $READTHEDOCS_OUTPUT/html
